[package]
name = "jlsoa"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"

[[bench]]
name = "soa_vs_aos_access"
harness = false

[dependencies]
structure_of_arrays = { path = "structure_of_arrays" }
structure_of_arrays_macro = { path = "structure_of_arrays_macro" }
